# Generated by Django 5.1.3 on 2025-01-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
