# Generated by Django 5.1.3 on 2025-01-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
