# Generated by Django 5.1.3 on 2025-01-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_activity_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('USER_CREATED', 'User Created'), ('USER_CREATED', 'User Deleted'), ('COURSE_CREATED', 'Course Created'), ('COURSE_DELETED', 'Course Deleted'), ('ENROLLED', 'Enrolled'), ('COMPLETED', 'Enrollment Completed')], max_length=50),
        ),
    ]
