# Generated by Django 5.1.4 on 2025-01-06 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_course_created_by_remove_course_thumbnail_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CUser',
        ),
    ]
