# Generated by Django 5.1.4 on 2025-01-06 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_cuser_user_course_created_by_course_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='created_by',
        ),
    ]
